server:
  port: 8080
spring:
  datasource:
    url: "jdbc:h2:file:./test1.db"
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG